### ISSUE TITLE
STEP Bible has a module called LXX_th

### ISSUE THREAD

**Issue by DavidHaslam** [pierre-amadio/LXX#2]
The **STEP Bible** repository includes a module called LXX_th

Aside: Before this is include in the **Master Repositories List** by CrossWire, please visit the wiki to obtain the connection details for FTP & HTTP.

**Comment by pierre-amadio** [comment]
I am sorry i do not understand this issue. Can you please clarify what may be the problem to fix ?

**Comment by DavidHaslam** [comment]
Not every issue is immediately a problem to fix.

My new issue was to share information that you might be unaware of. 

Similar SWORD modules can be compared to bring to light problems that might otherwise be missed by either development team. 

cf. Another LXX module that might be of interest is grclxxbrenteb which can be installed from the eBible.org repository.
